# Generated by Django 5.2.1 on 2025-06-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nome', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('endereco', models.CharField(max_length=128)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
