# Generated by Django 5.2.1 on 2025-06-19 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='idade',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
